spring:
  application:
    name: dubbo-provider1
  redis:
    database: 0
    host: 192.168.0.130
    port: 6379
    timeout: 2000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password:
  datasource:
    url: jdbc:mysql://192.168.0.130/testDB?useSSL=false&userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  type-aliases-package: com.dsys.entity
  mapperLocations: classpath:mapper/*.xml
server:
  port: 9095
  session:
    timeout: 30
dubbo:
  registry:
    protocol: zookeeper
    address: 192.168.0.130:2181
    id: registry-1
  protocol:
    port: 12345
    name: dubbo
    id: dubbo
    status: server
  application:
    name: dubbo-provider1
    id: dubbo-provider-id1
    qos-enable: true
    qos-port: 22222
  scan:
    basePackages: com.dsys.provider
api:
  service:
    version: 1.0.0