spring:
  application:
    name: dubbo-provider1
  datasource:
    url: jdbc:mysql://127.0.0.1/data?useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  type-aliases-package: com.dsys.dao
  mapperLocations: classpath:mapper/*.xml
server:
  port: 9090
dubbo:
  registry:
    protocol: zookeeper
    address: localhost:2181
    id: registry-1
  protocol:
    port: 12345
    name: dubbo
    id: dubbo
    status: server
  application:
    name: dubbo-provider1
    id: dubbo-provider-id1
    qos-enable: true
    qos-port: 22222
  scan:
    basePackages: com.dsys.provider
test:
  service:
    version: 1.0.0